apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: efo3-ols
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: efo3-ols
    spec:
      containers:
      - name: efo3-ols
        image: efo3-ols/efo3-ols
        imagePullPolicy: Always
        ports:
        - containerPort: 8080