
"@context":

ontologies:

## EFO

  - id: efo
    preferredPrefix: EFO
    title: Experimental Factor Ontology (v3-beta)
    uri: http://www.ebi.ac.uk/efo/
    description: "EFO version 3 beta"
    homepage: http://www.ebi.ac.uk/efo
    mailing_list: efo-users@lists.sourceforge.net
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
      - http://purl.obolibrary.org/obo/RO_0002202
    hidden_property:
      - http://www.ebi.ac.uk/efo/has_flag
    base_uri:
      - http://www.ebi.ac.uk/efo/EFO_
    reasoner: OWL2
    oboSlims: false
    ontology_purl: file:///opt/ols/ontologies/efo.owl
