prefix oio: <http://www.geneontology.org/formats/oboInOwl#>
prefix def: <http://purl.obolibrary.org/obo/IAO_0000115>
prefix owl: <http://www.w3.org/2002/07/owl#>

# Selects the owl:Class (as cls), the definition of the class and concatenates all x-refs into one string while filtering out blank classes, and group the output by the class and defintion




SELECT ?cls ?def (group_concat(?xref) as ?xrefs) 

WHERE 

	{
 	   ?cls a owl:Class .
	   OPTIONAL { ?cls oio:hasDbXref ?xref } .
	   OPTIONAL { ?cls def: ?def } .
 	  FILTER (!isBlank(?cls))
	}
	
GROUP BY ?cls ?def
