prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?term ?property ?value
WHERE {
  ?term a owl:Class ;
        ?property ?value .
  FILTER (?property = rdfs:label || ?property = oboInOwl:hasExactSynonym)
  FILTER (!isBlank(?term))
  FILTER NOT EXISTS { ?term owl:deprecated "true"^^xsd:boolean }
}
