prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?cls1 
WHERE
{
  ?cls1 a owl:Class .
  ?cls1 rdfs:label ?label . 
  ?cls1 rdfs:subClassOf <http://www.w3.org/2002/07/owl#Thing> . 
  FILTER EXISTS {?cls1 rdfs:subClassOf ?cls3 } .
  FILTER NOT EXISTS {?cls1 owl:deprecated "true"^^xsd:boolean} .
  FILTER (?cls1 != URI("http://www.ebi.ac.uk/efo/EFO_0000001"))
  }