name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ontology_qc:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.1
    steps:
      - uses: actions/checkout@v4
      - name: Run ontology QC checks
        env:
          DEFAULT_BRANCH: master
        run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' ROBOT_JAVA_ARGS=-Xmx6g gh_actions
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Pronto
        run: pip install pronto

      - name: Run Pronto sanity checks
        run: |
          python -c "
          import pronto
          
          # Load the ontologies
          efo_base = pronto.Ontology('efo-base.owl')
          efo_edit = pronto.Ontology('src/ontology/efo-edit.owl')
          
          print(f'Number of terms: {len(efo_base.terms())}')
          print(f'Ontology IRI: {efo_base.metadata.ontology_iri}')
          
          print(f'Number of terms: {len(efo_edit.terms())}')
          print(f'Ontology IRI: {efo_edit.metadata.ontology_iri}')
          "